### PR TITLE
Language fixes and firefox update 

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by jensens** [comment]
reference to FF 34 issue: plone/jenkins.plone.org#179

**Comment by gforcada** [comment]
@jensens @thet jenkins nodes are updated but there are some tests failing :-/ http://jenkins.plone.org/job/plone-5.1-python-2.7-robot/549

Should I revert the version bump?

**Comment by gforcada** [comment]
I'm running it again just to check if it was a hiccup...

**Comment by gforcada** [comment]
@jensens @thet the problem persists and switching to phantomjs seems to break another random set of tests... I will not be around during the weekend, so I don't feel comfortable leaving the tests broken... any suggestion?

**Comment by gforcada** [comment]
As the code is already on the nodes I will merge it, if it needs to be fixed a new pull request should be made.

**Comment by thet** [comment]
@gforcada tnx for upgrading!

@gforcada at http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/4744/robot/ the failures seem all to be related to:
"WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details."

Sounds like a browser /OS setup issue.

**Pull request merged**
